name: CI

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '.vscode/**'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  # Lint can run in parallel with Build.
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Format Check
        run: pnpm run format:check

  # Build installs all devDependencies and runs our full build pipeline.
  # We upload all `dist/` artifacts to GitHub, which can be shared by all dependent jobs.
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            packages/*/dist/**
            packages/*/*/dist/**
          if-no-files-found: error

  # Test depends on Build's output, which allows us to skip any build process!
  test:
    name: 'Test: ${{ matrix.os }} (node@${{ matrix.node_version }})'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16]
        include:
          - os: windows-latest
            node_version: 16
          - os: macos-latest
            node_version: 16
      fail-fast: false
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1

      - name: Setup node@${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3

      - name: Extract Artifacts
        run: ./.github/extract-artifacts.sh

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm run test
